# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Stormkeeper
email: d.belyakin@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Stormkeeper.ru - специализированный ресурс для Шаманов в World of Warcraft!
description_long: >-
  Здесь вы можете найти актуальную информацию по всем специализациям шамана, а также полезные статьи, новости и многое другое.
about_author: >
  Меня зовут [**Amani**](https://twitch.tv/amanizandalari), я являюсь админом крупнейшено русскоязычного Discord-сервера Шаманов WoW [Водоворот](https://discord.gg/8Bag6kT) и пишу гайды с 2018 года.
  Вместе со своей [командой](https://stormkeeper.ru/info/patrons.html) я занимаюсь написанием приоритетов заклинаний для Simcraft и [Raidbots](https://raidbots.com), а также занимаюсь переводом таких
  ресурсов, как [MythicTrap](https://mythictrap.com) и [WoWAnalyzer](https://wowanalyzer.com).


  Я близко сотрудничаю с англоязычным сообществом шаманов и являюсь MVP на серверах
  [Earthshrine](https://discord.gg/earthshrine) и [Ancestral Guidance](https://discord.gg/AcTek6e).


  Регулярно стримлю на [Twitch](https://twitch.tv/amanizandalari) и выкладываю ролики на
  [YouTube](https://youtube.com/channel/UC5IikzgR1TeED-DxPLqISHg). Подписывайтесь!


  Поддержать создание контента можно на [Boosty](https://boosty.to/amani) и [Patreon](https://www.patreon.com/amani_vodovorot). Так же вы можете получить различные бонусы, например доступ к Epic аккаунту [Raidbots](https://raidbots.com). Спасибо за вашу поддержку!

locale: ru_RU
logo: /assets/img/logos/sk_full.png
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
# github_username:  vodovorot-guides
discord_servername: Водоворот
youtube_username: Amani
discord_invite: https://discord.gg/8Bag6kT

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-pages
  - jekyll-target-blank
  - jemoji

paginate: 6
show_excerpts: true
excerpt_separator: <!--more-->
list_title: Блог

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
